### ISSUE TITLE
A small request

### ISSUE THREAD

**Issue by Ninja-FSE** [ahembree/ansible-hms-docker#12]
Dont know if this is possible or not, but it should!

How bout to add ability to route apps/services through Cloudflare Tunnel using [this](https://github.com/cloudflare/cloudflared) (https://github.com/cloudflare/cloudflared)

**Comment by ahembree** [comment]
I like this idea. I remember hearing about this Cloudflare product but forgot about it, definitely a great idea to remove the requirement of adding port-forwards for HTTP/S as my IPS is constantly alerting on attempted attacks to ports 80/443.

**Comment by ahembree** [comment]
Alright so I've done a bit of research on Cloudflare Tunnel...

I've decided to do a partial implementation of it to basically only support [Public hostnames](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/routing-to-tunnel/) using a [DNS record](https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/routing-to-tunnel/dns/).

Private networks will not be supported due to the [requirements](https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/), such as [installing WARP](https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/warp/) or doing [complicated networking things to get agentless to work](https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/agentless/). 

This means that you will only be able to use Tunnel for HTTP/S traffic, and not for Plex video traffic. However, using Cloudflare for Plex traffic (well, non-HTML content) is [also against their ToS](https://www.cloudflare.com/terms/#28-limitation-on-serving-non-html-content), so this is another reason that only HTTP/S traffic will be supported.

But once this is implemented, it will allow users to close ports 80/443 to their network!

**Comment by ahembree** [comment]
This has been added in https://github.com/ahembree/ansible-hms-docker/commit/d3e4f8adbf7f9cba30cc52cde4d4b01c007a4e40
