### ISSUE TITLE
Bad Gateway / Too many redirects

### ISSUE THREAD

**Issue by Callump01** [ahembree/ansible-hms-docker#14]
Hi there,

I'm almost brand new to Linux and deploying this project to my environment has been a valuable learning experience for me so far, so thank you for continuing to maintain it. If a total newbie like me can get 75% of the way to deployment, it speaks volumes as to the ease of use for your project.

With that said, I'm stuck on a weird issue with my domain reporting "Gateway Error" around 50% of the time and I'm not sure if this is down to my domain's DNS settings, Traefik configuration or even the Transmission setup. 

I am using a *.live domain and utilising Cloudflare for DNS + Tunnels, with the tunnel gateway appearing to report a valid connection.

[DNS Records](https://i.imgur.com/X0YZdsL.png)
[Tunnel Configuration](https://i.imgur.com/vUfC8HR.png) - Set to HTTPS results in Gateway Error, HTTP results in too many redirects (re-write from Traefik to force HTTPS?)

I am also utilising Mullvad VPN for transmission. Initially had issues with this, but after following [advice](https://github.com/haugene/docker-transmission-openvpn/issues/1355#issuecomment-823234469) the issues resolved and the container is now reporting healthy, and Traefik is configured with my external IP in the label for good measure.

SSL Certificate also appears to be valid and as such I have disabled staging for it.

I am trying to access Plex and Overseerr externally and 50% of the time, plex.{mydomain}.com returns a Cloudflare "Bad Gateway" error, although I can eventually access Plex if I refresh the page multiple times before it eventually goes back to not working again. I cannot access Overseerr externally at all though, and often times I am receiving a "Too many redirects" error which does lead me to believe that Traefik might be the issue here?

Even on the server I also cannot access any of the containers except for Plex using the configured domain without using the local IP address (127.0.0.1:PORT) - I suspect this may be me misconfiguring the DNS though?

Any ideas on some things I could check here?

Thanks very much,
Callum

**Comment by Callump01** [comment]
Just doing some more playing around, I think this is almost certainly something to do with SSL. I've changed the tunnel config to use HTTPS again and now plex.{domain.live is also reporting a Gateway error instead of semi-working as it did before.

**Comment by Callump01** [comment]
Another quick update, I set the SSL/TLS in Cloudflare to use 'Full' end-to-end encryption rather than 'Flexible' and this has changed things up a little bit. I'm now receiving just the message "Forbidden" when accessing Radarr, Bazarr, etc either internally or externally, although Overseerr and Plex (which should be externally accessible) still do report the Gateway Error.

**Comment by ahembree** [comment]
> [Tunnel Configuration](https://i.imgur.com/vUfC8HR.png) - Set to HTTPS results in Gateway Error, HTTP results in too many redirects (re-write from Traefik to force HTTPS?)

If you use the Cloudflare Tunnel container, you need to use HTTP when accessing the other containers (so it should look something like `HTTP://sonarr:8989` for example). As for the too many redirects, I'm not sure why that would be happening. When using the Tunnel container, traffic does not flow through Traefik. Keep this in mind before attaching containers such as Sonarr and Radarr to the Tunnel as this will bypass the Traefik IP allowlist. I personally only recommend attaching the Overseerr (and Authentik) containers to the Tunnel.

If it's a `502 Bad Gateway` error when attempting to access the Transmission UI, you may need to restart the `transmission-proxy` container. I'm not sure why this error occurs, but restarting that usually fixes it for me.

If it's a 523 error from Cloudflare, this usually means Cloudflare is having an issue accessing your network (usually if the container is not running or port-forwarding isn't configured correctly). More info on Cloudflare-specific errors can be found here: https://support.cloudflare.com/hc/en-us/articles/115003011431-Troubleshooting-Cloudflare-5XX-errors

> I'm now receiving just the message "Forbidden" when accessing Radarr, Bazarr, etc either internally or externally which is strange given my IP is in external-ipwhitelist.

For the `Forbidden` messages, this may be due to the allowed IPs by the Traefik allow-list, but by default it allows all RFC1918 private addresses.

> but for the first time I can access Overseerr both internally and externally.

The Overseerr container is an exception to the allow-list. This container basically allows `0.0.0.0/0`

> Even on the server I also cannot access any of the containers except for Plex using the configured domain without using the local IP address (127.0.0.1:PORT) - I suspect this may be me misconfiguring the DNS though?

Nope, this is a security feature by default to reduce the number of "listening" ports on the server. You can disable this by setting `container_expose_ports: yes` in your variables file. Setting this to `yes` will allow you to access the services/containers running on the host by it's `<IP>:<PORT>`

**Comment by ahembree** [comment]
Whoops sorry did not mean to close this

**Comment by Callump01** [comment]
Issue solved, thanks so much for your prompt help! Cleaned up the tunnel as suggested alongside DNS so that only Overseerr and Plex are permitted externally, also updated the docker-compose so that Plex uses the external IP whitelist. Going to do some more hardening through the week and test with some friends.

Can now access both Overseerr and Plex externally without issue. Didn't end up exposing the ports and I think that I'll just keep using the local IPs to access the other services whilst on my network.

Slight sidenote; I see that in Portainer the stack is marked as 'Limited' control (since it was deployed via docker-compose) so it cannot be modified there outside of basic controls. I know this can be changed with some manual editing but didn't want to get into that given my lack of experience with Linux. Not sure if this is intended or misconfiguration on my part, but it'd be awesome to have that control in future revisions :)

Just continuing with my configuration now and delving into the world of Linux permissions for my external drives... wish me luck... thanks again!

**Comment by ahembree** [comment]
Thanks for the feedback!

Glad you're learning something new and expanding your knowledge, seems like you have the drive to figure things out which is an amazing trait to have!

As for the Portainer control of the stack, I haven't really dove deep into that side of things. I started using Portainer when I started learning Docker since a GUI seemed really nice, but as I gained more and more experience I became more and more comfortable with the CLI which is all I use now, I haven't really touched Portainer for a few years.

I would personally recommend getting more familiar with the Docker CLI than relying on Portainer to manage stuff since not every Docker deployment will have Portainer available 😉

However, I will say that sometimes it's easier to get a shell within a container by using Portainer than it is by CLI, mainly because it takes a little bit of the guess work out of guessing which shell is available within the container.
