### ISSUE TITLE
Authentik not generating key file on install

### ISSUE THREAD

**Issue by sferguson524** [ahembree/ansible-hms-docker#17]
When I am enabling authenik, it's not autocreating the key and pgpassword files.

**Comment by ahembree** [comment]
Can you confirm and/or provide the following info:

* You must be using the [advanced configuration](https://github.com/ahembree/ansible-hms-docker#using-the-advanced-configuration) to enable Authentik
* You must have `traefik_ssl_enabled: yes` set in the configuration
* You must have the Authentik container enabled _OR_ setting `authentik_enabled: yes`

If the above criteria is met, can you provide the output of running the following command in the folder where you saved the hms-docker data (by default: `/opt/hms-docker`):

```bash
ls -al | grep authentik
```

**Comment by sferguson524** [comment]
Let me enable the traefik SSL and see if that worksSent from my iPhoneOn Mar 23, 2023, at 19:22, Aidan Hembree ***@***.***> wrote:﻿
Can you confirm and/or provide the following info:

You must be using the advanced configuration to enable Authentik
You must have traefik_ssl_enabled: yes set in the configuration
You must have the Authentik container enabled OR setting authentik_enabled: yes

If the above criteria is met, can you provide the output of running the following command in the folder where you saved the hms-docker data (by default: /opt/hms-docker):
ls -al | grep authentik

**Comment by sferguson524** [comment]
I was successful in getting the key and pgpasswords to generate when enabling SSL in the config .  Thank you for that.  However, I am still getting from the worker that the secret is still missing

**Comment by ahembree** [comment]
Thanks for bringing this up!

I've seen that error previously in my own logs but Authentik seemed to still work so I didn't think much about it and thought it may have been limited to only my installation 🤷‍♂️ appears that is not the case though.

I checked the [reference compose file](https://goauthentik.io/docs/installation/docker-compose) and I don't see the `AUTHENTIK_SECRET_KEY` environment variable being assigned to the worker container, but I also wasn't getting errors in the logs about the key not missing... so I think it's due to how they're specifying a `env_file` value in the compose file whereas it is not specified within this repos code.

After doing some testing, it does appear that this environment variable needs to be assigned to the worker container.

This should now be resolved in https://github.com/ahembree/ansible-hms-docker/commit/0a93df6ce315e24ffe6c374a235df447eaef8e42

**Comment by sferguson524** [comment]
So re-apply the ansible playbook and it shuld pull a new container?

**Comment by ahembree** [comment]
You will first need to update your copy of the repo by running `git pull` from within the repo folder, this will pull down the new changes. 

If you've already done this, then yes, re-applying the playbook will update the `docker-compose.yml` file and restart any containers if necessary!
