### ISSUE TITLE
Plex container external access not working

### ISSUE THREAD

**Issue by sferguson524** [ahembree/ansible-hms-docker#19]
Greetings,

Looks like when enabling plex for external access, it's stuck using the media net for outbound traffic.. I have the port NATted in my firewall, and an ACL set to allow the traffic thru to the docker host IP.  An NMAP scan shows that port as closed/filtered..  wondering if traefik is screwing me up somehow.

**Comment by ahembree** [comment]
The `media_net` is only used for internal communication between the individual containers, the container should be listening on port `32400/TCP` on all interfaces available on the container since there is no IP defined in the `ports` section of the compose file for the Plex container.

This means you just need to port forward port `32400/TCP` externally (or your port of choice) to the Plex servers internal IP and port `32400/TCP`. But it looks like you've already done this part.

I don't believe Traefik would be causing issues externally as Traefik only runs on ports `80/443`.

Since the external Plex service (I believe) only hits `<external_IP>:32400` directly, it would bypass Traefik as it doesn't hit the HTTP/S ports.

**Comment by ahembree** [comment]
I would also try using an external port scan tool, such as https://canyouseeme.org/ and see if it reports the port as being open. If not, maybe a router reboot is necessary to apply the port forward change?

I've had slight issues in the past where Plex reports it cannot connect to my server, but then I try it again and it works.

**Comment by sferguson524** [comment]
bah!  I found it.. Ubiquiti moved the NAT rules and I missed it when I cut over from my old plex server:
