### ISSUE TITLE
Huge disk space savings / optimization possible

### ISSUE THREAD

**Issue by xavpitz** [ahembree/ansible-hms-docker#89]
Hello,

The "Use Hardlinks instead of Copy" advanced "Media Management" option from radarr & sonarr is not working.

The consequence is that during torrent seeding, all huge video files are using 2x the space they could use is they were hardlinked one to the other ( /opt/hms-docker/apps/transmission/torrents <--> /opt/hms-docker/media_data/_library).
This drastically reduce the potential seeding time because of the disk space usage implications and/or the library capacity.

I think the hard-linking doesn't work because of the way those 2 folders are presented to the radarr & sonaar containers.
/opt/hms-docker/media_data/_library            -->  /data/media
/opt/hms-docker/apps/transmission/torrents --> /data/torrents

Within the containers, as those two folders appears as different filesystems, hardlinking is not possible.
This make radaar & sonaar fallback to copying the files over from torrents --> media.

Having a common volume for /data or something along those lines will probably solve this issue.

Regards,

**Comment by ahembree** [comment]
Thanks for the feedback, I'll try to figure something out but not sure when I'll get the time. 

Feel free to submit a pull request if you're able to figure out a solution.

**Comment by xavpitz** [comment]
I am a big newbie with github (and also with docker/ansible & co). I am just somehow good at Linux..
I had a look at some YT videos about how to do a "pull request" :). I am trying to do just that but it is quite a learning curve :)

Anyway, I was breaking my head how to do this the most efficiently, without breaking too much things...

My plan would be to use :
- /opt/hms-docker/media_data/_library (no change to the library path itself).
- /opt/hms-docker/media_data/_torrents (instead of /opt/hms-docker/apps/transmission/torrents) as the torrents repo.

Then restrict : 
- Plex (or other media server) containers to :
   /opt/hms-docker/media_data/_library. Probably nothing to be done here.
- Transmission container to :
   /opt/hms-docker/media_data/_torrents. This needs to be changed in the roles/hmsdocker/templates/docker-compose.yml.j2
   
This will probably require a stop of all containers & a 
"mv /opt/hms-docker/apps/transmission/torrents /opt/hms-docker/media_data/_torrents" at the OS level

For Radaar & Sonarr (and maybe some other containers that I don't know about) they need access to the whole : 
   /opt/hms-docker/media_data. This will enable them to hardlink from _torrents --> _library.
They don't need 2 volumes to be mounted anymore as this one will provide access to both of the directories.
   
Now I think most of the heavy lifting needs to be done in the docker-compose.yml.j2 but this looks super hard for me.
I may give it a try but it will probably fail or I will break a lot of things...

**Comment by xavpitz** [comment]
Well... I have tried something at least... But it fails.
https://github.com/ahembree/ansible-hms-docker/compare/master...xavpitz:ansible-hms-docker:hardlink_friendly
Somehow I don't understand the syntax how to build variables.
The additional ones I created are "empty"...

**Comment by ahembree** [comment]
I think I see what you're attempting to do so I'll try to think of a solution. The biggest issue is changing file paths around due to existing installations and stuff. I very much don't want my repo responsible for impacting peoples personal media libraries.

I don't personally use hardlinks or anything and don't want to break my existing setup, but I recently got a Raspberry Pi and (finally) confirmed this repo works on it, so I'll try to use that as a testbed for this

**Comment by ahembree** [comment]
Instead of having 3+ different folder variables for the downloads, what if there were a single downloads folder (`hms_docker_downloads_path: "{{ hms_docker_mount_path }}/downloads"` for example), and within this folder there was a folder for each download type (torrent, sabnzbd, nzbget).

This way, there is 1 variable that would handle parent directory and the containers will handle creating the leaf directories, such as:
* `/opt/hms-docker/media_data/downloads/torrent`
* `/opt/hms-docker/media_data/downloads/sabnzbd`
* `/opt/hms-docker/media_data/downloads/nzbget`

And these could be mounted in the containers like so:
```
- ${hms_docker_downloads_path}/torrent:/downloads
...
- ${hms_docker_downloads_path}/sabnzbd:/downloads
...
- ${hms_docker_downloads_path}/nzbget:/downloads
```

If we can get away with only modifying the download directory targets, that'd be preferred.

**Comment by xavpitz** [comment]
As long as the (new) "_downloads" and (current) "_library" are sub-directories of "media_data" the hardlinking
_downloads --> _library performed by radarr & sonarr & probably readarr should work by providing the whole
- media_data directory as volume to radarr & sonarr & probably readarr 
but restricted : 
- _downloads to the download apps
-  _library to the reader/player apps

**Comment by xavpitz** [comment]
Ok, I managed to pass the "make check" / "make apply" on my current "hardlink_friendly" branch.

I tried not to break the plex libraries (I can confirm that plex still finds the media) by not modifying the host:container _library mount points.
Not breaking the _downloads part will be more challenging because this is the folder that needs to be moved on the host layer.
It will at least require a "mkdir /opt/hms-docker/media_data/_downloads" & a "mv apps/transmission/torrents media_data/_downloads"

Thing is transmission broke because of the way I built the "hms_docker_downloads_path" variable which seems empty.
It tries to mount the host : /torrents (which is non existing) instead of the /opt/hms-docker/media_data/_downloads/torrents.

I'm not sure which file I need to modify : vars/default/main.yml or roles/hmsdocker/defaults/main/main.yml .
Both looks the same for me. I modified both. I also built two new variables in roles/hmsdocker/defaults/main/hmsd_advanced.yml . I'm pretty sure I miss some understanding in the way to concatenate text to build variables. It seems obvious, but it is not or I am missing something obvious.

**Comment by ahembree** [comment]
You will only ever need to modify the variables in `vars/custom` due to Ansible's variable precedence. The variables in `roles/hmsdocker/defaults` are just the defaults of all possible settings in the event someone doesn't declare or deletes a variable. I'm also currently working on a way to reorganize the variables so that additional hosts can be defined in the inventory with different host-level variables (basically allowing greater scalability to more systems from 1 playbook)

As for concatenating strings, here may be a helpful example:

```
var1: "this is"
var2: "a test"
combined_var: "{{ var1 }} {{ var2 }}"
```

Ansible I believe follows the Jinja templating syntax in a way, and the above `combined_var` variable would turn out to equal `this is a test`

**Comment by xavpitz** [comment]
Thanks for the help about the variable building. It was exactly as I expected.
Thing is I did a syntax mistake in the jinja file. I had a "${ xxxxxxx }" string instead of "{{ xxxxxxx }}" at one specific place.

So I managed to have something working but it is still not 100% to my liking.
With hindsight, I think that artificially limiting (with the host:container volume mappings) the apps to either _library or _downloads doesn't add much to the security but annoyingly prevents hard-linking & file move across both folders.

I will continue to work on this...

**Comment by ahembree** [comment]
Of course, thanks for trying to figure out a solution!

For what it's worth, you can reference `.env` file variables in the docker-compose file by using `${VAR_NAME}`. This is regular Compose syntax and is not handled by Ansible. There's a mix of Compose-style variable references and Ansible-style in the docker-compose file due to referencing some of the variables from the `.env` file. This was to help keep "secret" values out of the compose file and also allow people to change some things quickly in the .env file without having to do a full playbook run again

Going back through my compose file, I can see a few places to replace the Ansible reference with a .env reference, such as `hms_docker_media_path`

**Comment by KnuffigerMaxi** [comment]
```bash

maxi@hms01:~$ cd /opt/hms-docker/
apps/          compose_files/ media_data/    vpn_configs/   
maxi@hms01:~$ cd /opt/hms-docker/media_data/
maxi@hms01:/opt/hms-docker/media_data$ ls .lathr 
ls: cannot access '.lathr': No such file or directory
maxi@hms01:/opt/hms-docker/media_data$ ls -lathr
total 16K
drwxr-xr-x 3 root root 4,0K Aug 29 18:19 _downloads
drwxr-xr-x 4 root root 4,0K Aug 29 18:19 .
drwxr-xr-x 6 maxi maxi 4,0K Sep 18 19:02 ..
drwxr-xr-x 5 root root 4,0K Sep 18 19:42 _library
maxi@hms01:/opt/hms-docker/media_data$ cd _downloads/
maxi@hms01:/opt/hms-docker/media_data/_downloads$ ls -lathr
total 12K
drwxr-xr-x 3 root root 4,0K Aug 29 18:19 torrents
drwxr-xr-x 4 root root 4,0K Aug 29 18:19 ..
drwxr-xr-x 3 root root 4,0K Aug 29 18:19 .
maxi@hms01:/opt/hms-docker/media_data/_downloads$ cd torrents/
maxi@hms01:/opt/hms-docker/media_data/_downloads/torrents$ ls -lathr
total 12K
drwxr-xr-x 3 root root 4,0K Aug 29 18:19 ..
drwxr-xr-x 3 root root 4,0K Aug 29 18:19 .
drwxrwxr-x 6 maxi maxi 4,0K Sep 19 04:04 transmission
maxi@hms01:/opt/hms-docker/media_data/_downloads/torrents$ cd transmission/
maxi@hms01:/opt/hms-docker/media_data/_downloads/torrents/transmission$ ls -lathr
total 24K
drwxrwxr-x 2 maxi maxi 4,0K Aug 29 18:19 watch
drwxr-xr-x 3 root root 4,0K Aug 29 18:19 ..
drwxrwxr-x 3 maxi maxi 4,0K Sep 18 19:35 acdc-the-razors-edge
drwxrwxr-x 3 maxi maxi 4,0K Sep 19 04:04 incomplete
drwxrwxr-x 2 maxi maxi 4,0K Sep 19 04:04 Home.Alone.2.Lost.In.New.York.1992.1080p.BluRay.REMUX.AVC.DTS-HD.MA.5.1-FGT
drwxrwxr-x 6 maxi maxi 4,0K Sep 19 04:04 .
maxi@hms01:/opt/hms-docker/media_data/_downloads/torrents/transmission$ cd ../../../..
maxi@hms01:/opt/hms-docker$ cd media_data/
maxi@hms01:/opt/hms-docker/media_data$ cd _library/
maxi@hms01:/opt/hms-docker/media_data/_library$ ls
Movies  Music  TV_Shows
maxi@hms01:/opt/hms-docker/media_data/_library$ cd Movies/
maxi@hms01:/opt/hms-docker/media_data/_library/Movies$ ls
maxi@hms01:/opt/hms-docker/media_data/_library/Movies$
```

```bash

maxi@hms01:/opt/hms-docker/media_data/_library$ ls -lathr 
total 20K
drwxr-xr-x 2 root root 4,0K Aug 29 16:11 Movies
drwxr-xr-x 2 root root 4,0K Aug 29 16:11 TV_Shows
drwxr-xr-x 4 root root 4,0K Aug 29 18:19 ..
drwxr-xr-x 2 root root 4,0K Sep 18 19:42 Music
drwxr-xr-x 5 root root 4,0K Sep 18 19:42 .
maxi@hms01:/opt/hms-docker/media_data/_library$
```



Wie verlinke ich diese Movies?
Welcher Ort stelle ich in Arr Apps ein sowie in Jellyfin/Plex

**Comment by ahembree** [comment]
@KnuffigerMaxi please submit a new issue in English

**Comment by KnuffigerMaxi** [comment]
> @KnuffigerMaxi please submit a new issue in English

But it's about the topic of hard links

**Comment by ahembree** [comment]
For Transmission, it'd be:

```
/data/media_data/_downloads/torrents/transmission
```

For Movies in Radarr/Plex/Jellyfin, it'd be:

```
/data/media_data/_library/Movies
```

For TV Shows in Sonarr/Plex/Jellyfin, it'd be:

```
/data/media_data/_library/TV_Shows
```

This is the most I can help with this as everyone's setup will be different and helping setup configurations is outside the scope of this project. The guide used for implementing this is here: https://trash-guides.info/Hardlinks/Hardlinks-and-Instant-Moves/.

If there is an issue with the code, please submit an issue.
